/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;

/**
 * Guía de Aprendizaje 3 - Componentes del PC
 * @author LABORATORIO
 */
public class jfrmSupport extends javax.swing.JFrame {

    /**
     * Creates new form jfrmSupport
     */
    public jfrmSupport() {
        initComponents();
        this.setLocationRelativeTo(null);//localizacion
        this.setTitle("Componentes del PC");//Titulo
        this.setResizable(false);//cambiar tamaño
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblPiezas = new javax.swing.JLabel();
        jlblNomPiezas = new javax.swing.JLabel();
        jlblTituloConcepto = new javax.swing.JLabel();
        jlblC = new javax.swing.JLabel();
        jlblTituloFuncion = new javax.swing.JLabel();
        jlblF = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        jMenuComponentes = new javax.swing.JMenu();
        itemMotherboard = new javax.swing.JMenuItem();
        itemProcesador = new javax.swing.JMenuItem();
        itemRam = new javax.swing.JMenuItem();
        itemHdd = new javax.swing.JMenuItem();
        itemSsd = new javax.swing.JMenuItem();
        itemFuente = new javax.swing.JMenuItem();
        itemGpu = new javax.swing.JMenuItem();
        itemRed = new javax.swing.JMenuItem();
        itemCooler = new javax.swing.JMenuItem();
        itemVentilador = new javax.swing.JMenuItem();
        itemSonido = new javax.swing.JMenuItem();
        itemCmos = new javax.swing.JMenuItem();
        itemSata = new javax.swing.JMenuItem();
        itemAlimentacion = new javax.swing.JMenuItem();
        itemBios = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        itemAcerca = new javax.swing.JMenuItem();
        itemCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 540));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblPiezas.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jlblPiezas.setForeground(new java.awt.Color(255, 255, 255));
        jlblPiezas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPiezas.setText("Piezas del Ordenador");

        jlblNomPiezas.setBackground(new java.awt.Color(255, 102, 102));
        jlblNomPiezas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNomPiezas.setPreferredSize(new java.awt.Dimension(480, 290));

        jlblTituloConcepto.setBackground(new java.awt.Color(0, 0, 0));
        jlblTituloConcepto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblTituloConcepto.setForeground(new java.awt.Color(255, 255, 255));
        jlblTituloConcepto.setText("Concepto");

        jlblC.setBackground(new java.awt.Color(255, 255, 255));
        jlblC.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlblC.setText("<html><div style='width:300px; padding:8px;'>Concepto.</div></html>");
        jlblC.setOpaque(true);
        jlblC.setPreferredSize(new java.awt.Dimension(330, 110));

        jlblTituloFuncion.setBackground(new java.awt.Color(0, 0, 0));
        jlblTituloFuncion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblTituloFuncion.setForeground(new java.awt.Color(255, 255, 255));
        jlblTituloFuncion.setText("Función principal");

        jlblF.setBackground(new java.awt.Color(255, 255, 255));
        jlblF.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlblF.setText("<html><div style='width:300px; padding:8px;'>Funcion Principal.</div></html>");
        jlblF.setOpaque(true);
        jlblF.setPreferredSize(new java.awt.Dimension(330, 110));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblC, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblNomPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblF, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(249, Short.MAX_VALUE))
                    .addComponent(jlblPiezas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jlblTituloConcepto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblTituloFuncion)
                        .addGap(354, 354, 354))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlblPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblTituloConcepto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jlblNomPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblTituloFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblC, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMenuArchivo.setText("Archivo");

        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(itemAbrir);

        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(itemGuardar);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(itemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuComponentes.setText("Componentes del PC");

        itemMotherboard.setText("Motherboard");
        itemMotherboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMotherboardActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemMotherboard);

        itemProcesador.setText("Procesador");
        itemProcesador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProcesadorActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemProcesador);

        itemRam.setText("Memoria RAM");
        itemRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRamActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemRam);

        itemHdd.setText("Disco Duro (HDD)");
        itemHdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHddActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemHdd);

        itemSsd.setText("Unidad SSD");
        itemSsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSsdActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemSsd);

        itemFuente.setText("Fuente de Poder");
        itemFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFuenteActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemFuente);

        itemGpu.setText("Tarjeta de Video (GPU)");
        itemGpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGpuActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemGpu);

        itemRed.setText("Tarjeta de Red");
        itemRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRedActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemRed);

        itemCooler.setText("Cooler del Procesador");
        itemCooler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCoolerActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemCooler);

        itemVentilador.setText("Ventilador del Gabinete");
        itemVentilador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVentiladorActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemVentilador);

        itemSonido.setText("Tarjeta de Sonido");
        itemSonido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSonidoActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemSonido);

        itemCmos.setText("Batería CMOS");
        itemCmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCmosActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemCmos);

        itemSata.setText("Cable SATA");
        itemSata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSataActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemSata);

        itemAlimentacion.setText("Cable de Alimentación");
        itemAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlimentacionActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemAlimentacion);

        itemBios.setText("BIOS / UEFI");
        itemBios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBiosActionPerformed(evt);
            }
        });
        jMenuComponentes.add(itemBios);

        jMenuBar1.add(jMenuComponentes);

        jMenuAyuda.setText("Ayuda");

        itemAcerca.setText("Acerca del programa");
        itemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaActionPerformed(evt);
            }
        });
        jMenuAyuda.add(itemAcerca);

        itemCreditos.setText("Créditos");
        itemCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreditosActionPerformed(evt);
            }
        });
        jMenuAyuda.add(itemCreditos);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        JOptionPane.showMessageDialog(this, "Funcionalidad Abrir");
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        JOptionPane.showMessageDialog(this, "Funcionalidad Guardar");
    }//GEN-LAST:event_itemGuardarActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        int msg = JOptionPane.showConfirmDialog(null, "¿Desea salir del software?", "Salir", JOptionPane.YES_OPTION);
        if (msg == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemMotherboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMotherboardActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Motherboard");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/motherboard.png")));
        jlblC.setText("<html><div style='width:300px;'>Es la placa principal de la computadora donde se conectan todos los componentes internos.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Permitir la comunicación y el funcionamiento conjunto de todos los componentes del equipo.</div></html>");
    }//GEN-LAST:event_itemMotherboardActionPerformed

    private void itemProcesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProcesadorActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Procesador");
        jlblC.setText("<html><div style='width:300px;'>Es el componente encargado de interpretar y ejecutar las instrucciones de los programas.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Procesar datos, realizar cálculos y controlar el funcionamiento de la computadora.</div></html>");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cpu.png")));
    }//GEN-LAST:event_itemProcesadorActionPerformed

    private void itemRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRamActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Memoria RAM");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ram.png")));
        jlblC.setText("<html><div style='width:300px;'>Es una memoria temporal que almacena la información de los programas que están en uso.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Facilitar un acceso rápido a los datos para mejorar el rendimiento del sistema.</div></html>");
    }//GEN-LAST:event_itemRamActionPerformed

    private void itemHddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHddActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Disco Duro ");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Disco Duro.png")));
        jlblC.setText("<html><div style='width:300px;'>Es un dispositivo de almacenamiento que utiliza discos magnéticos para guardar información.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Almacenar de forma permanente el sistema operativo, programas y archivos del usuario.</div></html>");
    }//GEN-LAST:event_itemHddActionPerformed

    private void itemSsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSsdActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Unidad SSD");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Unidad SSD.png")));
        jlblC.setText("<html><div style='width:300px;'>Es un dispositivo de almacenamiento que utiliza memoria flash, sin partes móviles.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Guardar información de forma permanente con mayor velocidad y eficiencia que un HDD.</div></html>");
    }//GEN-LAST:event_itemSsdActionPerformed

    private void itemFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFuenteActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Fuente de Poder");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fuente.png")));
        jlblC.setText("<html><div style='width:300px;'>Es el componente que convierte la corriente eléctrica en la energía que necesita la computadora.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Suministrar y distribuir energía de manera segura a todos los componentes internos.</div></html>");
    }//GEN-LAST:event_itemFuenteActionPerformed

    private void itemGpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGpuActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Tarjeta de Video ");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjeta de video.png")));
        jlblC.setText("<html><div style='width:300px;'>Es un dispositivo especializado en procesar gráficos e imágenes.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Generar y mejorar la calidad de las imágenes, videos y videojuegos que se muestran en el monitor.</div></html>");
    }//GEN-LAST:event_itemGpuActionPerformed

    private void itemRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRedActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Tarjeta de Red");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjeta red.png")));
        jlblC.setText("<html><div style='width:300px;'>Es un dispositivo que permite conectar la computadora a una red.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Envía y recibe datos para acceder a Internet o comunicarse con otros equipos.</div></html>");
    }//GEN-LAST:event_itemRedActionPerformed

    private void itemCoolerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCoolerActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Cooler del Procesador");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cooler.png")));
        jlblC.setText("<html><div style='width:300px;'>Es un sistema de enfriamiento formado por un disipador y un ventilador para el procesador.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Mantener una temperatura adecuada del CPU y evitar el sobrecalentamiento.</div></html>");
    }//GEN-LAST:event_itemCoolerActionPerformed

    private void itemVentiladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentiladorActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Ventilador del Gabinete");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ventilador.png")));
        jlblC.setText("<html><div style='width:300px;'>Es un ventilador instalado dentro del gabinete para mejorar la circulación del aire.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Expulsar el aire caliente e introducir aire fresco para enfriar los componentes internos.</div></html>");
    }//GEN-LAST:event_itemVentiladorActionPerformed

    private void itemSonidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSonidoActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Tarjeta de Sonido");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjeta sonido.png")));
        jlblC.setText("<html><div style='width:300px;'>Es un dispositivo que procesa las señales de audio de la computadora.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Permitir la reproducción y grabación de sonido mediante altavoces, audífonos y micrófonos.</div></html>");
    }//GEN-LAST:event_itemSonidoActionPerformed

    private void itemCmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCmosActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Batería CMOS");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Bateria CMOS.png")));
        jlblC.setText("<html><div style='width:300px;'>Es una pequeña batería ubicada en la motherboard que alimenta la memoria CMOS.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Conservar la fecha, la hora y la configuración del BIOS/UEFI cuando la computadora está apagada.</div></html>");
    }//GEN-LAST:event_itemCmosActionPerformed

    private void itemSataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSataActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Cable SATA");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cable SATA.png")));
        jlblC.setText("<html><div style='width:300px;'>Es un cable de datos utilizado para conectar dispositivos de almacenamiento a la motherboard.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Transferir datos entre el disco duro o SSD y la placa base.</div></html>");
    }//GEN-LAST:event_itemSataActionPerformed

    private void itemAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlimentacionActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("Cable de Alimentación");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cable de alimentacion.png")));
        jlblC.setText("<html><div style='width:300px;'>Es un cable que transporta energía eléctrica desde la fuente de poder a los componentes.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Proporcionar la energía necesaria para el funcionamiento de cada dispositivo interno.</div></html>");
    }//GEN-LAST:event_itemAlimentacionActionPerformed

    private void itemBiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBiosActionPerformed
        jlblNomPiezas.setText("");
        jlblPiezas.setText("BIOS");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BIOS.png")));
        jlblC.setText("<html><div style='width:300px;'>Es el firmware que se ejecuta al encender la computadora y administra la configuración básica del hardware.</div></html>");
        jlblF.setText("<html><div style='width:300px;'>Inicializar los componentes del equipo y cargar el sistema operativo para iniciar la computadora.</div></html>");
    }//GEN-LAST:event_itemBiosActionPerformed

    private void itemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaActionPerformed
        JOptionPane.showMessageDialog(this, "Programa para conocer los componentes principales del PC.", "Acerca del programa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemAcercaActionPerformed

    private void itemCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreditosActionPerformed
        JOptionPane.showMessageDialog(this, "Tarea Guía de Aprendizaje 3\nComputación\nJose MANUEL Ortiz Tejeda", "Créditos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmSupport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemAcerca;
    private javax.swing.JMenuItem itemAlimentacion;
    private javax.swing.JMenuItem itemBios;
    private javax.swing.JMenuItem itemCmos;
    private javax.swing.JMenuItem itemCooler;
    private javax.swing.JMenuItem itemCreditos;
    private javax.swing.JMenuItem itemFuente;
    private javax.swing.JMenuItem itemGpu;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemHdd;
    private javax.swing.JMenuItem itemMotherboard;
    private javax.swing.JMenuItem itemProcesador;
    private javax.swing.JMenuItem itemRam;
    private javax.swing.JMenuItem itemRed;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemSata;
    private javax.swing.JMenuItem itemSonido;
    private javax.swing.JMenuItem itemSsd;
    private javax.swing.JMenuItem itemVentilador;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuComponentes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblC;
    private javax.swing.JLabel jlblF;
    private javax.swing.JLabel jlblNomPiezas;
    private javax.swing.JLabel jlblPiezas;
    private javax.swing.JLabel jlblTituloConcepto;
    private javax.swing.JLabel jlblTituloFuncion;
    // End of variables declaration//GEN-END:variables
}
